### ISSUE TITLE
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #3 'other' in call to _th_ior_

### ISSUE THREAD

**Issue by arikanev** [memray/OpenNMT-kpg-release#14]
Hi - When running the eval script presented in the README I get the above error -stacktrace below.

`  var = torch.tensor(arr, dtype=self.dtype, device=device)
Translating 32/308
Traceback (most recent call last):
  File "kp_gen_eval.py", line 164, in <module>
    opt=opt
  File "/home/ari/DKG/OpenNMT-kpg-release/onmt/translate/translator.py", line 372, in translate
    batch, data.src_vocabs, attn_debug
  File "/home/ari/DKG/OpenNMT-kpg-release/onmt/translate/translator.py", line 593, in translate_batch
    return_attention=attn_debug or self.replace_unk)
  File "/home/ari/DKG/OpenNMT-kpg-release/onmt/translate/translator.py", line 766, in _translate_batch
    beam.update_finished(last_step=(step+1==max_length))
  File "/home/ari/DKG/OpenNMT-kpg-release/onmt/translate/beam_search.py", line 217, in update_finished
    self.top_beam_finished |= self.is_finished[:, 0].eq(1)
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #3 'other' in call to _th_ior_`

**Comment by memray** [comment]
Ahh, I don't know where this comes from. I suspect it is due to version difference of Pytorch. Could you try checking the data type of those tensors and making them consistent? I hope this helps.

Rui

**Comment by arikanev** [comment]
Yeah thanks - So one of them is a tensor of Bools, the other is of type uint8. I'm thinking I should convert the Falses to 0, and the Trues to 1?

**Comment by arikanev** [comment]
changing the Bool tensor to Byte to .byte() seems to have worked - at least it's running - not sure if it messes the model up somehow. Will close the issue for now since it runs. thanks
