### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by shizhediao** [memray/OpenNMT-kpg-release#4]
Hi Rui,
I am running the command below:
`CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py -config config/train/config-rnn-keyphrase-one2seq-diverse.yml`
Have you encountered this error and do you know how to solve it?

> [2019-11-15 06:59:48,581 INFO] number of examples: 100000
[2019-11-15 07:01:43,754 INFO] Step 100000/100000; acc:  60.37; ppl:  5.19; xent: 1.65; lr: 0.00002; 14635/1246 tok/s; 213352 sec
Process SpawnProcess-3:
Traceback (most recent call last):
  File "train.py", line 212, in <module>
    main(opt)
  File "train.py", line 94, in main
    p.join()
  File "/home/diaoshizhe/anaconda3/envs/pt11p36/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/home/diaoshizhe/anaconda3/envs/pt11p36/lib/python3.6/multiprocessing/popen_fork.py", line 50, in wait
Traceback (most recent call last):
  File "/home/diaoshizhe/OpenNMT-py/train.py", line 154, in run
    single_main(opt, device_id, batch_queue, semaphore)
  File "/home/diaoshizhe/OpenNMT-py/onmt/train_single.py", line 164, in main
    trainer.report_manager.tensorboard_writer.close()
AttributeError: 'NoneType' object has no attribute 'close'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/diaoshizhe/anaconda3/envs/pt11p36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/diaoshizhe/anaconda3/envs/pt11p36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/diaoshizhe/OpenNMT-py/train.py", line 160, in run
    error_queue.put((opt.gpu_ranks[device_id], traceback.format_exc()))
  File "/home/diaoshizhe/anaconda3/envs/pt11p36/lib/python3.6/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/home/diaoshizhe/anaconda3/envs/pt11p36/lib/python3.6/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/home/diaoshizhe/anaconda3/envs/pt11p36/lib/python3.6/traceback.py", line 612, in format
    yield from self.format_exception_only()
  File "/home/diaoshizhe/anaconda3/envs/pt11p36/lib/python3.6/traceback.py", line 567, in format_exception_only
    yield _format_final_exc_line(stype, self._str)
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
KeyboardInterrupt
  File "/home/diaoshizhe/anaconda3/envs/pt11p36/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "train.py", line 196, in signal_handler
    raise Exception(msg)
Exception: 

-- Tracebacks above this line can probably
                 be ignored --

Traceback (most recent call last):
  File "/home/diaoshizhe/OpenNMT-py/train.py", line 154, in run
    single_main(opt, device_id, batch_queue, semaphore)
  File "/home/diaoshizhe/OpenNMT-py/onmt/train_single.py", line 164, in main
    trainer.report_manager.tensorboard_writer.close()
AttributeError: 'NoneType' object has no attribute 'close'

Thanks!
![image](https://user-images.githubusercontent.com/18120087/68951472-1ba0de00-07f9-11ea-9750-e1d090b240ee.png)

**Comment by memray** [comment]
Hmm as your training has finished, I don't think it matters much. I think it's because the tensorboard is improperly closed in other training sub-processes which leads to this error. Disable the tensorboard (turn it off in your config.yaml) if you don't need it and hope it helps.
